# ---------------------------------------------------------------------------
# Nightly_Update_and_Backup.py
# Created on: 2014-02-14 14:24:59.00000
#   (base script generated by ArcGIS/ModelBuilder)
# Description: This script calls several other scripts to download
# outside information and then update the parcel layer's information
# each night.
# It then publishes the newly updated geodatabases to the O:, S:,
# and Z: drives and turns off the machine.
# ---------------------------------------------------------------------------

from Assmt_Extract_Download import main as Assmt_Extract_Download
from Update_Address_Information import main as Update_Address_Information
from Parcel_Centroids_Creation import main as Parcel_Centroids_Creation
from Geodatabase_Backup_And_Update import main as Geodatabase_Backup_And_Update
from Timered_Shutdown import main as Timered_Shutdown
  
def main():
  try:

    print "Starting the Nightly_Update_and_Backup script."
  
    print "Running Assmt_Extract_Download."
    Assmt_Extract_Download()
    print "Assmt_Extract_Download complete."
  
    print "Running Update_Address_Information."
    Update_Address_Information()
    print "Update_Address_Information complete."

    print "Running Parcel_Centroids_Creation."
    Parcel_Centroids_Creation()
    print "Parcel_Centroids_Creation complete."

    print "Running Geodatabase_Backup_And_Update."
    Geodatabase_Backup_And_Update()
    print "Geodatabase_Backup_And_Update complete."
    
    print "Shutting down now."
    Timered_Shutdown()
  
  except Exception as e:
    # If an error occurred, print line number and error message
    import traceback, sys
    tb = sys.exc_info()[2]
    print "Line %i" % tb.tb_lineno
    print e.message
  
if __name__ == "__main__":
  main()

time.sleep(10)
exit()